services:
  # Backend service
  - type: web
    name: cp-stats-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://cp-stats-frontend.onrender.com
      - key: PORT
        value: 10000

  # Frontend service
  - type: web
    name: cp-stats-frontend
    env: node
    buildCommand: cd Frontend && npm install && npm run build
    startCommand: cd Frontend && npm run preview
    envVars:
      - key: VITE_BACKEND_URL
        value: https://cp-stats-backend.onrender.com 